package decoder

import (
	"errors"
	"image"

	"github.com/schaepher/ocr/document"
)

// ErrInvalidLocToken is returned when LOC token sequence is malformed.
var ErrInvalidLocToken = errors.New("invalid LOC token sequence")

// ErrUnsupportedFormat is returned when the raw output format is not recognized.
var ErrUnsupportedFormat = errors.New("unsupported output format")

// Decoder converts raw model output into a structured Document.
//
// Each VLM model family (PaddleOCR-VL, Qwen2.5-VL, InternVL3, etc.)
// has its own output format and needs a separate Decoder implementation.
type Decoder interface {
	// Decode parses raw model output and returns a structured Document.
	// raw is the full text generated by the model.
	// imageSize is the original image dimensions used for coordinate scaling.
	Decode(raw string, imageSize image.Point) (*document.Document, error)
}
